# Generated by Django 5.2.13 on 2026-07-14 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=255, unique=True)),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('refill_rate', models.FloatField(default=1)),
                ('algorithm', models.CharField(choices=[('token', 'tocken_bucket'), ('fixed', 'fixed_window')], default='token', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteLimitAdmin',
            fields=[
                ('routelimit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='limiter.routelimit')),
            ],
            bases=('limiter.routelimit',),
        ),
    ]
